import Link from "next/link";
import { IconArrowLeft as ArrowLeft, IconInbox as Inbox, IconUsers as Users } from "@tabler/icons-react";
import { notFound } from "next/navigation";
import { getApplications, getCompany } from "@/lib/store";

export const dynamic = "force-dynamic";

export default async function ApplicationsPage({ params }: { params: Promise<{ company: string }> }) {
  const { company: slug } = await params;
  const [company, applications] = await Promise.all([getCompany(slug), getApplications(slug)]);
  if (!company) notFound();
  return <main className="min-h-screen bg-cream px-5 pb-20 pt-32"><div className="mx-auto max-w-6xl"><Link href={`/${slug}`} className="flex items-center gap-1 text-sm font-semibold text-black/50 hover:text-black"><ArrowLeft size={17} /> Back to hiring page</Link><div className="mt-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-black/35">{company.name}</p><h1 className="mt-2 text-4xl font-black tracking-[-0.055em] sm:text-6xl">Applications</h1></div><div className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-semibold shadow-sm"><Users size={17} /> {applications.length} candidate{applications.length === 1 ? "" : "s"}</div></div>
  {applications.length === 0 ? <div className="mt-12 flex min-h-[320px] flex-col items-center justify-center rounded-[28px] border border-dashed border-black/15 bg-white/50 text-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-white"><Inbox size={24} /></span><h2 className="mt-5 text-xl font-bold">No applications yet</h2><p className="mt-2 max-w-sm text-sm leading-6 text-black/45">Share your hiring page. New candidates will appear here as soon as they apply.</p></div> : <div className="mt-10 overflow-hidden rounded-[24px] border border-black/[0.07] bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-black/[0.07] bg-black/[0.02] text-xs uppercase tracking-wider text-black/40"><tr><th className="px-5 py-4">Candidate</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Answers</th><th className="px-5 py-4">Applied</th></tr></thead><tbody className="divide-y divide-black/[0.07]">{applications.map((application) => <tr key={application.id} className="align-top"><td className="px-5 py-5"><p className="font-bold">{application.name}</p><a className="mt-1 block text-xs text-black/45 hover:text-black" href={`mailto:${application.email}`}>{application.email}</a></td><td className="px-5 py-5"><span className="rounded-full bg-lime/60 px-3 py-1.5 text-xs font-semibold">{application.roleTitle}</span></td><td className="max-w-md px-5 py-5"><div className="space-y-3">{application.answers.map((answer) => <div key={answer.question}><p className="text-xs font-semibold text-black/40">{answer.question}</p><p className="mt-1 whitespace-pre-wrap leading-5 text-black/75">{answer.answer}</p></div>)}</div></td><td className="whitespace-nowrap px-5 py-5 text-xs text-black/45">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(application.createdAt))}</td></tr>)}</tbody></table></div></div>}</div></main>;
}
